#include <iostream>
#include <iomanip>
#include <fstream>
#include <armadillo>
#include <string>
#include "../src/headers/math33.H"
#include "../src/headers/nanoshell.H"
#include "../src/headers/cup.H"

/*
g++ -Wall -I/usr/include/ -L/usr/local/lib electricfieldtest.cxx -o tim -lgsl -lgslcblas -lm -larmadillo
*/

using namespace std;

int main(int argc, char** argv) {
    // Initialize variables for input parameters
    // Create an instance of the nanosphere class

    double omemi, omema, E0, rho, *fro, tpump, T, eps3, eps_b;
    char mtl[16], mdl[16], hst[16], sol[16], active[16];

    nanosphere  simulation;
    simulation.init();
    
    fstream nano, time;

    nano.open("../data/input/nanosphere_eV.dat", ios::in);
    time.open("../data/input/time.dat", ios::in);
    
    nano>>simulation.r1>>simulation.Dome>>simulation.ome_0>>simulation.G>>omemi>>omema>>mtl>>mdl>>active>>sol>>E0>>rho>>hst;
    time>>T>>tpump;  
        
    simulation.set_metal(mtl,mdl,1);
    simulation.set_active(active);
    eps3=simulation.set_host(sol);
    eps_b=simulation.set_host(hst);
    
    // Perform the time_behavior calculation

 
    fro=simulation.frohlich(omemi, omema, eps_b, eps3, rho);
    // Calculate the saturation electric field Esat
    double ntau1, ntau2;
    ntau2 = 2./simulation.Dome;
    ntau1 = 5.*ntau2;

    double nEsat = sqrt(1/(fabs(simulation.G)*ntau1));
    E0 = nEsat*(1e-9);
    //double nEsatup2 = 1/(fabs(simulation.G)*ntau1);

    //Border check
    int omeN=1000;
    int omi, ch=1, o1=0, o2=0, oB=0;
    double  omeeV, dome  = (omema-omemi)/omeN, Ome, Omem=0., ome;
    double ome1, ome2;
    
        dome  = (omema-omemi)/100000;
// TODO: what follows has to go in a subroutine find_ome1_ome2(ns, omemi, omema, hst, sol, rho)
        for (omi=0; omi<=100000; omi++){
            omeeV = omemi + omi*dome;
            Omem = Ome;
            Ome = simulation.find_Omega(omeeV, hst, sol, rho);
            ome  = omeeV/simulation.Ome_p;
            if (o1==1 && Omem != 0) ch  = Omem*Ome/fabs(Omem*Ome);
            if (fabs(Ome)>1.e-30 && o1==0){
                ome1=ome;
                o1=1;
                }
            if (fabs(Ome)<1.e-30 && o2==0 && o1==1 && oB==1){
                ome2=ome-dome/simulation.Ome_p;
                o2=1;
                }
            if (ch < 0 && o1==1 && oB==0) {
                simulation.omeB     = ome;
                oB=1;
                }
            }
        if (fabs(simulation.G)<fabs(fro[1])) {
            ome1=simulation.omeB/simulation.Ome_p+dome;
            ome2=simulation.omeB/simulation.Ome_p-dome;
            }
        if (ome1*simulation.Ome_p==omemi || ome2 ==0){
            std::cout<<"Fatal! the frequency range is too small!"<<std::endl;
            exit(78);
            }
//----------------------------------

    // Inform the user about the test
    cout << "Calculating the time_behavior up to "<<T<<" ps\n";
    cout << "                switching the pump on at "<<tpump<<"ps ...\n\n";
    cout << "* Beware if  "<<simulation.G<<" is greater than "<<fro[1]<<"\n";
    cout << "* you can get exponential behaviors in the\n";
    cout << "* analytical results for some frequencies\n\n";

    cout << "Parameters:\n";
    cout << "  Metal model: " << mdl << "\n";
    cout << "  Metal type: " << mtl << "\n";
    cout << "  Core material: " << hst << "\n";
    cout << "  Solvent: " << sol << "\n";
    cout << "  Radius ratio: " << rho << "\n\n";


    cout << "Running frequency loop test...\n";
    // // Número de frecuencias en el barrido:
    // int Nfreq = 40;
    // double omeeV = 0, pss = 0;

    // // Paso en frecuencia (eV)

    // double width  = omema - omemi;            // ancho actual
    // double center = simulation.ome_0;         // centro deseado

    // double omemin = center - 0.5 * width;             // nuevo mínimo
    // double omemax = center + 0.5 * width;             // nuevo máximo

    //  double dome = (omemax - omemin) / (Nfreq - 1);


    //     dyna.open("../data/output/numtime.dat", std::ios::out);
		

	// 	dyna<<"# * FREQUENCY TEST * "<<std::endl;
	// 	dyna<<"#"<<std::endl;
	// 	dyna<<"# file generated by ** cup.H ** "<<std::endl;
	// 	dyna<<"#"<<std::endl;
	// 	dyna<<"# PARAMETERS: "<<std::endl;
	// 	dyna<<"# G = "<< simulation.G <<std::endl;
	// 	dyna<<"# E0 = "<<E0<<std::endl;
    //     dyna<<"# Esat = "<<nEsat<<std::endl;
	// 	dyna<<"# a "<<mdl<<" model was used for "<<mtl<<std::endl;
	// 	dyna<<"# ------------- "<<std::endl;
	// 	dyna<<"# omeeV\t Dip_max"<<std::endl;
	// 	dyna<<"#"<<std::endl;

    //for (int i = 0; i < Nfreq; ++i) {
        //omeeV = omemin + i * dome;

        // Llamas a probetest con esta frecuencia



        simulation.omegatest(mdl, mtl, hst, nEsat, tpump, E0, ome1, ome2, sol, rho);
    //    simulation.omegatest(mdl, mtl, hst, nEsat, tpump, E0, sol, rho);

    // std::vector<double> omeeV_list, pss_list;

    // std::ifstream steady("../data/output/numtime.dat");
    // std::string line;
    // while (std::getline(steady, line)) {
    //     if (line.size() == 0 || line[0] == '#') continue; // saltar comentarios
    //     std::stringstream ss(line);
    //     ss >> omeeV >> pss;
    //     omeeV_list.push_back(omeeV);
    //     pss_list.push_back(pss);
    // }
    // steady.close();

    // std::fstream dyna;
    //     dyna.open("../data/output/probetime.dat", std::ios::out);
		

	// 	dyna<<"# * FREQUENCY TEST * "<<std::endl;
	// 	dyna<<"#"<<std::endl;
	// 	dyna<<"# file generated by ** cup.H ** "<<std::endl;
	// 	dyna<<"#"<<std::endl;
	// 	dyna<<"# PARAMETERS: "<<std::endl;
	// 	dyna<<"# G = "<< simulation.G <<std::endl;
	// 	dyna<<"# E0 = "<<E0<<std::endl;
    //     dyna<<"# Esat = "<<nEsat<<std::endl;
	// 	dyna<<"# a "<<mdl<<" model was used for "<<mtl<<std::endl;
	// 	dyna<<"# ------------- "<<std::endl;
	// 	dyna<<"# t (ps)\t omeeV\t omeeV/Ome_p\t Bigome\t Dip_max"<<std::endl;
	// 	dyna<<"#"<<std::endl;

        // for (size_t k = 0; k < omeeV_list.size(); ++k) {

        // omeeV = omeeV_list[k];
        // pss = pss_list[k];
        
        // Llamas a probetest con esta frecuencia
        simulation.omegatest_N(mdl, mtl, hst, nEsat, tpump, E0, ome1, ome2, sol, rho);
    // }
    //    dyna.close();

    // Output the results

    // Save the results to a file
    ofstream output("results/time_behavior.log");
    if (output.is_open()) {
        output << "Steady-state polarizability calculation results:\n";
	output << "  Metal model: " << mdl << "\n";
        output << "  Metal type: " << mtl << "\n";
        output << "  Core material: " << hst << "\n";
        output << "  Time range: [0, " << T << "] ps\n";
        output << "  The pump is switched on at "<<tpump<<" ps\n";
        output << "  Solvent: " << sol << "\n";
        output << "  Radius ratio: " << rho << "\n";
        output << "\nCheck simulation output for detailed results.\n";
        output.close();
        cout.precision(10);
        cout.setf(ios::fixed);
        cout <<"> Output saved in the following files:"<<endl;
	    cout<<">   ../data/output/anltime.dat"<<endl;
	    cout<<">   ../data/output/anlfunc.dat"<<endl;
	    cout<<">   ../data/output/numtime.dat"<<endl;
	    cout<<">   ../data/output/numfunc.dat"<<endl;
        cout<<"> log saved in results/time_behavior.log"<<endl;
    } else {
        cerr << "Error: Could not open file for writing results.\n";
    }

    return 0;
}
